GET http://localhost:8080/estudantes

###

POST http://localhost:8080/estudante/new
Content-Type: application/json

{
  "id": "1",
  "nome": "Arthur Bingas",
  "senha": "dawdawdaw",
  "cpf": "12345678902",
  "matricula": "19200000",
  "curso": "Ciência da Computação",
  "semestre_ingresso": "19.2"
}

###

DELETE http://localhost:8080/estudante/delete/648d03a75e3b7240052376a9